[tool.black]
line-length = 100
target-version = ["py310"]
extend-exclude = ""

[tool.isort]
profile = "black"
line_length = 100
known_first_party = []
src_paths = ["GDP-ForecasterSARIMAX"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E203", "W503"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"